name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x      

      - name: Lint, test, and build
        run: |
          deno task test
          deno task build

      # - uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage/coverage-final.json
      #     fail_ci_if_error: true
